---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-boot-demo
  name: spring-boot-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-boot-demo
    spec:
      containers:
      - image: docker.io/maartensmeets/spring-boot-demo
        name: spring-boot-demo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-boot-demo
  name: spring-boot-demo
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: spring-boot-demo
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: spring-boot-demo
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /java
spec:
  rules:
  - http:
      paths:
      - path: /java
        backend:
          serviceName: spring-boot-demo
          servicePort: 8080
