pipeline {
    parameters{
        string(name: 'sp_appid', defaultValue: '', description: 'Azure Service Principal ID')
        string(name: 'sp_apppwd', defaultValue: '', description: 'Azure Service Principal password')
        string(name: 'sp_tenantid', defaultValue: '', description: 'Azure Service Principal tenant ID')
        string(name: 'sp_subscriptionid', defaultValue: '', description: 'Azure Service Principal subscription ID')
        string(name: 'aks_name', defaultValue: '', description: 'Cluster name')
        string(name: 'rg_name', defaultValue: '', description: 'Resource group name')
    }
    agent any
    stages {
        stage('Login in Azure') {
             sh '''
                   az account clear
                   az login --service-principal --username ${params.sp_appid} --password ${params.sp_apppwd} --tenant ${params.sp_tenantid}
                   az account set -s ${params.subscription_id}
                '''
        }
        stage('Geting kubernetes credentials') {
            sh '''
                  az aks get-credentials -n ${params.aks_name} -g ${params.rg_name}
               '''
        }
    }
}